# Generated by Django 2.2 on 2019-04-30 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('numname', models.CharField(max_length=64)),
                ('service_time_start', models.TimeField()),
                ('service_time_end', models.TimeField()),
                ('type', models.CharField(choices=[('G', '去机场'), ('C', '去城区')], max_length=8)),
                ('interval', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('identify', models.CharField(choices=[('user', '用户'), ('busdriver', '大巴司机'), ('employee', '公司员工')], default='用户', max_length=32)),
                ('mobile', models.CharField(max_length=32, unique=True)),
                ('realname', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=64, unique=True)),
                ('seat', models.IntegerField(default=40)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line')),
            ],
        ),
        migrations.CreateModel(
            name='PriceOfLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('validation', models.CharField(choices=[('y', '已检票'), ('n', '未检票')], default='n', max_length=8)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Departure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.User')),
            ],
        ),
        migrations.AddField(
            model_name='departure',
            name='busdriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.User'),
        ),
        migrations.AddField(
            model_name='departure',
            name='shuttle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Shuttle'),
        ),
    ]
