# Generated by Django 2.1.1 on 2019-01-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('busdriver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.User')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('destination', models.CharField(max_length=128)),
                ('service_time_start', models.TimeField()),
                ('service_time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceOfLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=64, unique=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='departure',
            name='shuttle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Shuttle'),
        ),
    ]
