# Generated by Django 2.1.1 on 2019-01-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190118_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identify',
            field=models.CharField(choices=[('user', '用户'), ('busdriver', '大巴司机'), ('employee', '公司员工')], default='用户', max_length=32),
        ),
    ]
