# Generated by Django 2.1.1 on 2019-01-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_user_identify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1234567, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='刘世隆', max_length=128),
            preserve_default=False,
        ),
    ]
