# Generated by Django 2.1.1 on 2019-01-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190118_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identify',
            field=models.CharField(choices=[('user', '用户'), ('busdriver', '大巴司机'), ('employee', '公司员工')], default='user', max_length=32),
        ),
    ]
