# Generated by Django 2.1.1 on 2019-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190119_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='interval',
            field=models.TimeField(default='0:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='numname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='type',
            field=models.CharField(choices=[('G', '去机场'), ('C', '去城区')], default='G', max_length=8),
            preserve_default=False,
        ),
    ]
