# Generated by Django 2.1.1 on 2019-01-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190119_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='destination',
        ),
    ]
