# Generated by Django 2.1.1 on 2019-01-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_line_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofline',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line'),
        ),
    ]
