# Generated by Django 2.1.1 on 2019-01-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190119_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Line'),
        ),
    ]
