# Generated by Django 2.1.1 on 2019-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190119_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='validation',
            field=models.CharField(choices=[('y', '已检票'), ('n', '未检票')], default='n', max_length=8),
        ),
    ]
